version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: kaspi-api
    ports:
      - "8080:8080"
    volumes:
      - ./.env:/app/.env
    restart: unless-stopped
